vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user_avatar:
            uri_prefix: /users/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
